version: 2.1

orbs:
  codecov: codecov/codecov@3.2.4

jobs:
  build-test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean install
      - run:
          name: Test
          command: mvn test
      - codecov/upload:
          file: /target/site/jacoco/jacoco.xml

  docs:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: install1
          command: sudo add-apt-repository ppa:openjdk-r/ppa
      - run:
          name: install2
          command: sudo apt-get update
      - run:
          name: install3
          command: sudo apt-get install openjdk-11-jdk-headless -y
      - run:
          name: Build-docs
          command: javadoc src/main/java/fr/univavignon/pokedex/api/* -d docs
      - persist_to_workspace:
          root: .
          paths: docs

  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: docs/
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "sbaa.oussama07@gmail.com"
            git config user.name "oussama-sbaa"
      - add_ssh_keys:
          fingerprints:
            - "07:46:fd:0c:37:7d:00:03:f2:17:a4:e0:2f:fc:45:60"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dist docs/

workflows:
  version: 2
  c-i:
    jobs:
      - build-test
      - docs
      - docs-deploy:
          requires:
            - build-test
            - docs
          filters:
            branches:
              only: master
